/! See PSA_SHW-0F Document , Page 027F
WL= 1
BL= 0
Desktop_Only= 1

/! See PSA_SHW-0F Document , Page 0280
Mode= 0   /! 0= Local 1= WorldWide (Only Allow Writeing New Data in Temp DB)
CAC0= 1

/! See PSA_SHW-0F Document , Page 0281
CBC1= 1
CCCC= 0

/! See PSA_SHW-0F Document , Page 0282 
DDDD= 0
CEC4= 0
CFC5= 0
ACAA= 1

/! See PSA_SHW-0F Document , Page 0283-0288
BFDE= "ALT", "SLL", "PR-A-BA-GA-SEC-Rev20"
BFDF= 2
RTCCLK= 1
CBCCRA= 0
IPSCRE= 0x1100
SRACCDIR= "Root/0A"


/! See PSA_SHW-0F Document , Page 0289 
CONNCOMSP= "R2"
RFTSP= "Beta1" /! D: 2025-11-01 S2
SFTSP= "Beta1" /! D: 2025-11-24 S2
WCSP== "R2"
WSSP= "R1"
LFACC= "R2"
SMSP= ""  /! "B1" D: 2026-01-10;

BL {
  0x0000
}

WL {
  0x0001
}




/! ' 0x0000 ' is a List ID , Avalible 2 types 
/! 1 - Is ID (Max IDS = HEX: 0xFFFF; DEC: 43666;)
/! 2 Is Name (u can Use 16 Character Letters and Numbers String, Not Start With Num)
/! For More Info, See PSA_SHW-0F Document , Page 028A 
0x0000 {
  Name= "Example Device"

  SN= "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
  MAC= "00 00 00 00 00 00"
  IP0= "0.0.0.0"
  WebProvider= "Telekommunikation Der Russischen Regierung"
  Cert= "0A.crtf", "0B.pem", "0C.crt", "0D.cer"
  TimeZone= "+", "0100"
  Theme= "Light"
  Screen= "0800x0600"
}

0x0001 {
  Name= "ARTEM_x92 WorkStation"
  
  Manufacturer= "Alfa92 Electronics"
  Model= "A92 Ultra"
  CodeName= "PolarIce"

  
  SN= "00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F"
  PN= "00 01 02 03 04 05 06 07"
  MAC= "00 01 02 03 04 05"
  IMEI0= "00 01 02 03 04 05 06 07"
  IMEI1= "00 01 02 03 04 05 16 17"
  HOST= ""
  IP0= "92.92.92.92"
  IP1= "0000:0101:0202:0303:0404:0505:0606:0707"
  WebProvider= "Alfa92 Telecomm"
  Location= "Showa Japanese Station / Antarctica"
  Cert= "root.crtf"
  TimeZone= "+", "0300"
  Lang= "DE"
  OS= "Linux"
  Theme= "Dark"
  Screen= "1024x0768"
}
